apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sms-page-viewer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sms-page-viewer.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sms-page-viewer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sms-page-viewer.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: page-viewer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PORT
              value: {{ .Values.service.port | quote }}
            - name: BACKEND_URL
              value: {{ .Values.backendUrl | quote }}
            - name: WAREHOUSE_URL
              value: {{ .Values.warehouseUrl | quote }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
