apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sms-k8s-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sms-k8s-exporter.labels" . | nindent 4 }}
