apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sms-warehouse.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sms-warehouse.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.databaseUrl | quote }}
